# Update your profiles.yml file (~/.dbt/profiles.yml) with this configuration:

sql_server_project:
  outputs:
    dev:
      database: dbt_analytics
      driver: 'ODBC Driver 17 for SQL Server'
      host: localhost
      port: 1433
      schema: dbo
      threads: 1
      type: sqlserver
      windows_login: true
      encrypt: false
      trust_cert: true
  target: dev
