image: python:3.12


stages:
  - validate
  - deploy

variables:
  DBT_PROFILES_DIR: "$CI_PROJECT_DIR"
  DBT_PROJECT_DIR: "$CI_PROJECT_DIR/sql_server_project"

before_script:
  - apt-get update
  - apt-get install -y curl gnupg2
  - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  - curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
  - apt-get update
  - ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt


# Validate dbt project (no database needed)
validate_project:
  stage: validate
  script:
    - echo "🔍 Variables check..."
    - echo "DB_HOST:" $DB_HOST
    - echo "DB_USER:" $DB_USER
    - echo "DB_PASSWORD:" ${DB_PASSWORD:0:3}***
    - cd $DBT_PROJECT_DIR
    - dbt deps
    - dbt parse  
    - echo "✅ dbt project syntax is valid!"



    
  only:
    - merge_requests
    - main

# Deploy (manual, with database)
deploy_models:
  stage: deploy
  script:
    - cd $DBT_PROJECT_DIR
    - dbt deps
    - dbt debug
    - dbt run
    - dbt test
  only:
    - main
  when: manual