sql_server_project:
  outputs:
    dev:
      database: dbt_analytics
      driver: 'ODBC Driver 17 for SQL Server'
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: 1433
      schema: dbo
      threads: 1
      type: sqlserver
      windows_login: false
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      encrypt: false
      trust_cert: true
  target: dev